'use client'

import './globals.css'
import AppWalletProvider from './components/AppWalletProvider'
import { ReactQueryProvider } from './react-query-provider'
import Header from './components/Header'
import {Footer} from './components/Footer'
import 'react-toastify/dist/ReactToastify.css'
import { ToastContainer } from 'react-toastify'
import { Provider } from 'react-redux'
import { store } from './store'
import {Inter} from 'next/font/google'
import { ThemeProvider } from './components/Theme-provider'
const metadata = {
  title: 'votee',
  description: 'Generated by create-solana-dapp',
}
const inter = Inter({ subsets: ['latin'] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='min-h-screen flex flex-col'>
      <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
        <ReactQueryProvider>
          <Provider store={store}>
            <AppWalletProvider>
              <Header />
              <main className="flex-1">{children}</main>
             <Footer />
            </AppWalletProvider>
          </Provider>
        </ReactQueryProvider>
      </ThemeProvider>
      </body>
    </html>
  )
}
